apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller-node
spec:
  selector:
    matchLabels:
      service: kafka-controller
  replicas: 3
  serviceName: kafka-controller
  template:
    metadata:
      labels:
        service: kafka-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - aws
                - key: service
                  operator: In
                  values:
                    - ec2
                - key: region
                  operator: In
                  values:
                    - us-west-2
                - key: availability_zone
                  operator: In
                  values:
                    - us-west-2a
      containers:
        - name: main
          image: sloopstash/kafka:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: generic
                  key: cluster_id
            - name: LOG_DIR
              value: /opt/kafka/log
            - name: KAFKA_OPTS
              value: "-Djava.net.preferIPv4Stack=True"
          volumeMounts:
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: kafka-controller-supervisor
              mountPath: /etc/supervisord.d/kafka-controller.ini
              subPath: kafka-controller-supervisor
            - name: kafka-controller-server
              mountPath: /opt/kafka/conf/server-reference.conf
              subPath: kafka-controller-server
            - name: kafka-controller-data
              mountPath: /opt/kafka/data
            - name: kafka-controller-script
              mountPath: /opt/kafka/script
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
          ports:
            - containerPort: 9093
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: supervisor-server
          configMap:
            name: kafka-controller
        - name: kafka-controller-supervisor
          configMap:
            name: kafka-controller
        - name: kafka-controller-server
          configMap:
            name: kafka-controller
        - name: kafka-controller-data
          persistentVolumeClaim:
            claimName: kafka-controller-data
        - name: kafka-controller-script
          hostPath:
            path: /opt/kickstart-kafka/script/controller
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: kafka-controller-data
      spec:
        storageClassName: kafka-controller-data
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
