apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    service: controller
spec:
  clusterIP: None
  ports:
    - name: listner
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    service: controller
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    service: broker
spec:
  clusterIP: None
  ports:
    - name: listner
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    service: broker